---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml
driver:
  name: docker
platforms:
  - name: sles-16
    image: sles-16-ansible-docker
    pre_build_image: false
    dockerfile: Dockerfile
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
  playbooks:
    converge: converge.yml
    verify: verify.yml
scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: ansible
